### ISSUE TITLE
Why ViewMouse doesn't handle the movable procedure instead of the Adornment?

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3342] opened 2024-03-20 12:36 UTC
Before it was possible to move a `Toplevel` without `Border` or a `Window` with/out `Border`. Now only `Adornment` can handle this, which in my opinion isn't the right behavior. Should be the `View` itself responsible to handle this based on the `Arrangement` setting.
So the logic on the `OnMouseEvent` in the `Adornment` should be on the `OnMouseEvent` of the `ViewMouse.cs` file.

**Comment by tig** [comment] 2024-03-20 17:37
What is the end-user use case you are considering here?

**Comment by BDisp** [comment] 2024-03-20 17:44
In the BackgroundWorker scenario I use a WorkerApp which is a Toplevel without Border to proof the moveable is also possible. Now it can't move. I already have a solution for this and I'll submit a PR. Maybe you agree with the change that is only 2 or 3 lines.

**Comment by BDisp** [comment] 2024-03-20 21:33
Is there any reason why the Padding isn't allowing to move the view if it's the only adornment? It overrides the `OnMouseEvent` to only set focus to the parent. I don't want to change this if it has a special meaning for you.

**Comment by BDisp** [comment] 2024-03-20 23:14
`Toplevel` created by the `Application.Init` shouldn't be moveable, otherwise it will behave badly because it represent all the available space on a terminal.

**Comment by tig** [comment] 2024-03-20 23:34
> Is there any reason why the Padding isn't allowing to move the view if it's the only adornment? It overrides the `OnMouseEvent` to only set focus to the parent. I don't want to change this if it has a special meaning for you.
> 
> I think that if it doesn't have any subviews will be possible to move the view if it's moveable.

I actually think it's debatable whether margin should support drag. 

It's all debatable. 

I decided it made no sense for padding.

**Comment by BDisp** [comment] 2024-03-21 00:02
> I actually think it's debatable whether margin should support drag.
> 
> It's all debatable.
> 
> I decided it made no sense for padding.

Sure, but I only referring if the Padding it's the only Adornment. In this case I think clicking in the Padding is possible to move the view, otherwise a view with only a Padding never can move the view if it's moveable. I think it's the right procedure, but I could be wrong.

**Comment by tig** [comment] 2024-03-21 00:35
> `Toplevel` created by the `Application.Init` shouldn't be moveable, otherwise it will behave badly because it represent all the available space on a terminal.

Right. Another reason Toplevel as a class was a regrettable design choice.

With 'Arrangment' it's an easy fix.

**Comment by tig** [comment] 2024-03-21 00:38
> > Is there any reason why the Padding isn't allowing to move the view if it's the only adornment? It overrides the `OnMouseEvent` to only set focus to the parent. I don't want to change this if it has a special meaning for you.
> > 
> > I think that if it doesn't have any subviews will be possible to move the view if it's moveable.
> 
> I actually think it's debatable whether margin should support drag. 
> 
> It's all debatable. 
> 
> I decided it made no sense for padding. 

More context:

Margin and Padding are typically invisible to the user. Border typically, literally, shows a border. I believe users will be surprised if they click and drag on something invisible and it starts dragging. 

See "the principle of least surprise"

**Comment by BDisp** [comment] 2024-03-21 11:18
> More context:
> 
> Margin and Padding are typically invisible to the user. Border typically, literally, shows a border. I believe users will be surprised if they click and drag on something invisible and it starts dragging.
> 
Margin is always invisible unless the effect3D is implemented. Padding could ne not always invisible but could have subviews.
Border is really the correct class where the `OnMouseEvent` should handle the moveable view.
Maybe the only exception is in the case where the view has no adornments and the color is highlighted from the background color and so the user has a visible area to visualize the movement effect.

> See "the principle of least surprise"

I already saw, thanks. I suggest the only the Border to be responsible to move the view. The exception is on views without adornments which the user want make it visible from the superview background color and want move it. If the view has Margin and Border the mouse must be over the Border thickness to could move the view. What do you think?

**Comment by tig** [comment] 2024-03-21 13:36
I concur regarding Border: I'll change things so only `Border` handles move/size asap.

However, I do not think the ability to drag a view with no Border should be built-in. Here's why:

- It's not discoverable. Yes, we could invent a way of making such a view indicate it can be moved/dragged visually, but that's just more complexity.
-There isn't a keyboard interface (that's visible). With #2537 we'll have the ability to support keyboard move/resize.
- It's very rare use-case.
- Just add a border to the view. It could be with just `Thickness (0, 1, 0, 0)` and with `Title = string.Empty`, for example*.

If this Issue is not fixed, there's an alternative if someone wants a non-border view to be movable with the mouse:

- Just use the `MouseEvent` event, or override `OnMouseEvent` in the view (in your case `WorkerApp`) to handle the move/drag themselves. 

For this reason, I'd like to close this issue as "by design'. 

*Regarding `Title` visibiility: I am not happy with the way the `Border` currently determines whether to draw/not draw the Title. I plan on adding some sort of setting that enables adjusting the border "style". Once I get the time to upgrade `Border` to be based on a set of subviews, the Title will be rendered as a `Label`. Thus, `view.Border.TitleLabel.Visible = false` will turn off the Title.

**Comment by tig** [comment] 2024-03-21 13:48
For example this completely addresses your desired UI using even less screen real estate (instead of using a Label to duplicate "TItle", just use `Title`):

![ekQwBPw 1](https://github.com/gui-cs/Terminal.Gui/assets/585482/3fac6b91-9f36-411c-aae9-c20b1494d261)

**Closed** 2024-03-26 18:14 UTC
Labels: bug
