### ISSUE TITLE
Create new `ScrollBar` based on a new `Scroll` and remove `ScrollBarView/ScrollView`

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2489] opened 2023-04-04 04:01 UTC
This is a sub-issue of:

- #2994 

## Requires

- #3323 

# Design

Scroll bar support will be based on three views: `ScrollBar` which is a composite of two buttons supporting continuous button press and a `Scroll`, which is just the "middle" part of a scroll bar.

These views are described below.

## `Scroll`

A new View that represents the "inside part" of a scroll bar, minus the arrow buttons

It should look like the existing `ScrollBarView` (but better).

<img width="281" alt="image" src="https://github.com/gui-cs/Terminal.Gui/assets/585482/40489eb1-a7c3-49ee-a2d6-6be3c9891235">

and

<img width="6" alt="image" src="https://github.com/gui-cs/Terminal.Gui/assets/585482/2b9cb0b2-2e6e-482d-8ff0-6d352cc08090">

It should have the following fields/methods/events (roughly):

* `public Orientation Orientation {get ;set;}` - Determines the Orientation of the scroll.
* `public int Size { get;set;}` - The size of content the scroll represents.
* `public int Position { get; set;} - The position, relative to `Size`, to set the scrollbar at.
* `public event PositionChanging`
* `public event PositionChanged`
* `public event SizeChanged`

It'd be cool (but not required) for all the glyphs and styling to be configurable; similar to how `Slider.SliderStyle` works.

The names/types of these should match `Slider` as much as is reasonable for consistency. 

It must not have any internal knowledge of `ScrollBar` or the other views `ScrollBar` contains.

## `ScrollBar` 

A new View that is a composition of 3 subviews

- `public Button Decrease { get; set; }` - Has `WantContinousButtonPressed` set to true
- `public Button Increase { get; set; }` - Has `WantContinousButtonPressed` set to true
- `public Scroll Scroll { get; set; }` 

Exposes `public Orientation Orientation { get; set; }`. This is used to layout the 3 views correctly depending on orientation. Obvioulsy it also needs to change the glyph each of the two buttons have to be correct for orientation too.

This will be just a regular View that can be added as a subview to another view. It will not need any of the `Host` complexity that `ScrollBarView` has.

Exposes:

* `public Orientation Orientation {get ;set;}` - Determines the Orientation of the scroll. A passthrough to  `scrollBar.Scroll.Orientation`.
* `public int Size { get;set;}` - The size of content the scrollbar represents. Just a passthrough to `scrollBar.Scroll.Size`.
* `public int Position { get; set;} - The position, relative to `Size`, to set the scrollbar at.
* `public event PositionChanging`
* `public event PositionChanged`
* `public event SizeChanged`

Keyboard bindings for the most common operations should be included:

- `Key.UpArrow`, `Key.DownArrow`, `Key.LeftArrow`, `Key.RightArrow`, `Key.PageUp/Down`

Specialized mouse code should not be needed because the 2 `Button`s and the `Scroll` should "just work".

## `View` changes required

Once `ScrollBar` is ready, `View` can be modified to have two built-in scroll bars that can be enabled by the developer. These will wire in to the content scrolling support enabled in #3323.

The two `ScrollBar` views will be added to `Padding` using computed layout. 

Exposes:

* `public ScrollBar HoriztonalScrollBar { get; set ;}; // Actually created inside of `Padding`
* `public ScrollBar VerticalScrollBar { get; set ;}; // Actually created inside of `Padding`

We will expand `ViewportSettings` with more flags that control the behavior of the scroll bars:

* `AutoHoriztonalScrollBar`, `AutoVerticalScrollBar`, and `AutoBothScrollBars` - when set auto show/hide

We should be able to use `Pos.Function()` to automatically ensure the bottom-right-corner is handled correctly depending on `Viewport` and `ContentSize` and the above settings.

For a scroll bar to be visible the `Padding.Thickness` needs to be adjusted and `ScrollBar.Visible` needs to be set. Using `ScrollBar.VisibleChanged`, we should be able to automatically adjust `Padding.Thickness` when a developer sets `HorizontalScrollBar.Visible = true/false`, etc...

## Delete `ScrollBarView` and `ScrollView`

Once `ScrollBar` is ready, we will delete `ScrollBarView` and `ScrollView` from the project, updating any built-in Views and Scenarios that use them.

**Comment by tig** [comment] 2023-04-16 15:30
Also:

> ScrollBar and ScrollView are still mostly working in https://github.com/gui-cs/Terminal.Gui/pull/2361 but need a bunch of changes to really work well again.

? In addition, I'd like to revisit the pattern used. The new Frames concept should allow any View to have scrolling without having to add and manage a bunch of scroll objects as is needed today. The idea being the Adornments Frame (temporarily called BorderFrame) can host scroll bars and the work I've done to decouple Bounds from Frame such that Bounds could have a non-zero Location should make scrolling much easier on devs.

> So, for now https://github.com/gui-cs/Terminal.Gui/pull/2361 will be no-bueno relative to scroll bar use cases.

**Comment by BDisp** [comment] 2024-02-01 14:24
We need to decide whether the scrollbars will be inside the `Border` or inside the `Padding` adornment. Regardless of where it resides, the adornment can only be designed after executing the layout of the content subviews. `Border` already calls `OnRenderLineCanvas` after the content has finished being drawn, but `Padding` does not.

**Comment by BDisp** [comment] 2024-02-01 18:05
I started developing the scroll bar added to `Padding`. The problem is that `FindDeepestView` does not search for sub-views within `Padding`. Any news on this?

![image](https://github.com/gui-cs/Terminal.Gui/assets/13117724/4e7d7c7e-46a3-4a1a-969b-4f10242dff3b)

**Comment by BDisp** [comment] 2024-02-01 19:50
ahah I already can capture the mouse click in the `Padding` but see the first effect I get 😄 

https://github.com/gui-cs/Terminal.Gui/assets/13117724/1051ee77-f10d-448e-b76d-f43c7a61e90d

**Comment by BDisp** [comment] 2024-02-01 19:57
With negative bounds is working but I have to avoid drawing.

https://github.com/gui-cs/Terminal.Gui/assets/13117724/09508bd7-f755-4161-80fb-52c0adfe3e0f

**Comment by BDisp** [comment] 2024-02-03 00:16
Using the `Margin` location as (0,0) whatever is the `View.Frame` will invalidade any way of using the `LayoutSubViews` on the `Adornments`. I think the `Margin.Frame` should always equal to the `View.Frame`. The only doubt is if the `Margin` thickness isn't empty the `View.Frame` should be equal to the `Margin.Frame`. I think it should.

**Comment by dodexahedron** [comment] 2024-02-03 01:07
I would tend to agree that bars should be drawn inside, beginning from the inside of where Margin ends, and should not be included in width or height calculations.If padding is non-zero, they would thus be drawn in the padding area.Any margin would be beyond the bar.

**Comment by BDisp** [comment] 2024-02-03 17:40
> * We will figure out how to enable `Bounds.Location` to be negative (or introduce a `ContentArea`)

I need to decide what of the both properties could allow to have negative location. I started with the `Bounds` and it's working as expected and I created the `ContentArea` property with only a getter. Personally I would prefer to use the `Bounds` to use negative location and use the `ContentArea` with a empty location. This will implies that I change all the call to the `ClipToBounds` to `ClipToContentArea`. Do you all agree with this?

**Comment by BDisp** [comment] 2024-02-03 18:14
I already having it working.

https://github.com/gui-cs/Terminal.Gui/assets/13117724/b8519344-cfb0-4c83-8f7d-f1ff52d5bec3

**Comment by BDisp** [comment] 2024-02-03 19:47
See the difference if `TextFormatter.Draw` `fillRemaining` parameter is true. All the `ContentArea` is filled with whitespaces showing a perfect rectangle. I think I'll create a `FillRemaining` property to be configurable by the views. I think the default should be true in the `View.Draw` method. The `_contentBottomRightCorner` is already fixed here.

https://github.com/gui-cs/Terminal.Gui/assets/13117724/ba8743c2-035b-4d41-87bc-daf2eaa9a993

**Comment by BDisp** [comment] 2024-02-14 11:35
> I need to decide what of the both properties could allow to have negative location. I started with the `Bounds` and it's working as expected and I created the `ContentArea` property with only a getter. Personally I would prefer to use the `Bounds` to use negative location and use the `ContentArea` with a empty location. This will implies that I change all the call to the `ClipToBounds` to `ClipToContentArea`. Do you all agree with this?

@tig, @tznind , @dodexahedron I need a final decision on which of both should using negative location. I'm using the `Bounds` for negative location and if the majority decide other way that will imply more difficult to me to fix, because when location has X, Y or both negative we need to compensate the Width and Height by increasing and decreasing their length.
If anybody say nothing until today I'll consider that you want using Bounds to deal with negative location and I won't revert that behavior. Thanks.

**Comment by BDisp** [comment] 2024-02-14 13:34
> I think using `Bounds` (which WILL be renamed to `ContentArea` per #3169) is the right way to go.
> 

I wouldn't recommended rename it because when Bounds have negative location the Width/Height will be different than it's actually we know. So, they may really have different values from each other.

> Question: How far are you going in changing existing sample code to use the built-in View scrolling with your PR? Similarly, what are you doing to light up new use-cases. For example, making it so that `CategoryList.EnableVerticalScrollBar = true` (or equivalent) in `UICatalog.cs` is all that's needed to have the scroll bar just work?
> 

I have a lot of work of this and I'll open a PR asap, maybe today for you see what I'm doing. I'm not using a bool to show/hide the scroll bars but a enum of scroll bar type (None, Both, Vertical, Horizontal).

> I ask because, until we do 3 or four use-cases like that I don't think we'll really know the answer to your question
> 

Yes I know, I'll try to submit a PR today if possible.

> > **Edit:** I'm also using the `Padding` because is the most near of the `ContentArea` and much more easy to deal.
> 
> I like this. It was how I envisioned it working.

Good, we are in syntony.

**Comment by BDisp** [comment] 2024-02-15 23:04
@tig I'll get rid of this constructor. Do you have any objection?

`public ScrollBarView (View host, bool isVertical, bool showBothScrollIndicator = true)`

It will only have a default constructor and a `internal` constructor that will only used by the `View` class.

`internal ScrollBarView (View host, ScrollBarType scrollBarType)`

**Comment by tig** [comment] 2024-02-16 01:36
> @tig I'll get rid of this constructor. Do you have any objection?
> 
> `public ScrollBarView (View host, bool isVertical, bool showBothScrollIndicator = true)`
> 
> It will only have a default constructor and a `internal` constructor that will only used by the `View` class.
> 
> `internal ScrollBarView (View host, ScrollBarType scrollBarType)`

I don't understand why you are asking about this. I have no problem removing that constructor.

However, to me, if `View` supports scrolling natively, then there's no need for `ScrollBarView` to exist at all. 

But until I see your code, I have no idea how you're approaching this.

**Comment by BDisp** [comment] 2024-02-16 01:57
> I don't understand why you are asking about this. I have no problem removing that constructor.
> 
Great.

> However, to me, if `View` supports scrolling natively, then there's no need for `ScrollBarView` to exist at all.
> 
I'm still using it to draw the bars. Have you other idea for that?

> But until I see your code, I have no idea how you're approaching this.

I'm struggling with some issues after I've merged from v2_developer, but I'm doing my best as possible.

**Comment by tig** [comment] 2024-02-16 02:20
I see. That makes sense. I always ScrollBarView and ScrollView mixed up.

**Comment by tig** [comment] 2024-02-16 02:22
Why would ScrollBarView need a "host"? Why isn't that just its SuperView?

**Comment by BDisp** [comment] 2024-02-16 08:07
> Why would ScrollBarView need a "host"? Why isn't that just its SuperView?

The SuperView is the Padding but the data is from the Parent. With the default constructor I want allow that any view can add it where the user want. I can remove the View parameter and in this case it will always added to the Padding but that will prevent it can be added into the Border. The host field will be only internal to identify the SuperView.

**Comment by BDisp** [comment] 2024-02-16 13:41
> I'll wait to comment further until I see the code. But I do have one other suggestion: Feel free to clone `ScrollBarView` into `ScrollBar` (better name) and make it incompatible with the old way of doing things if you can make the new model simpler.

I already created a `ViewScrollBar` file as `Partial View`, but kept the `ScrollBarView` file as is. But that can be changed of course.

**Comment by BDisp** [comment] 2024-04-01 16:28
I'm reopen this because I'm convinced that the `SetRelativeLayout` should handled the location offset, although until now it wasn't never used. This is only to proof that and not for be merged, of course.

https://github.com/gui-cs/Terminal.Gui/assets/13117724/5a0a9c30-981a-42fb-a394-80319eb4df7f

**Closed** 2024-11-19 20:41 UTC
Labels: v2
