### ISSUE TITLE
Border: can't change border color in window by Border.BorderBrush

### ISSUE THREAD

**Issue by Lamborge** [gui-cs/Terminal.Gui#2342] opened 2023-02-12 10:05 UTC
**Describe the bug**
The color of the Border depends on the ColorScheme of Window, when you try to change the color of the Border through the BorderBrush property, nothing happens.

**Comment by BDisp** [comment] 2023-02-12 12:50
The `Border` frame really depends on the `ColorScheme` of `Window`. If you only want to have a empty border around you can use the `Padding` or `BorderThickness`. If you use both the `BorderThickness` is the more outer and the `Padding` is in the middle. The `BorderBrush` foreground color is used on the `BorderThickness` and the background color is used on the `Padding`.

**Comment by Lamborge** [comment] 2023-02-12 13:36
I only need to change the color of the foreground of border, why not just do it via the Border.BorderBrush specification?

**Comment by BDisp** [comment] 2023-02-12 13:44
Because the `Border.BorderBrush` hasn't nothing to do with the `Window.ColorScheme`. If you only want to change the Window frame color you have to change the `Window.ColorScheme` to another value. The already existing on on the API (Colors.Base, Colors.Toplevel, etc...) or create your custom `ColorScheme`.

**Comment by Lamborge** [comment] 2023-02-12 13:58
I only want to change color of `Border` in `Window` by setting `Border.BorderBrush`, but color of `Border` depends on `Window.ColorScheme.Norman.Foreground`

**Comment by BDisp** [comment] 2023-02-12 14:04
Looping :-)

**Comment by Lamborge** [comment] 2023-02-12 14:08
Okay, thanks for the replies, I'm closing the issue

**Comment by tig** [comment] 2023-02-13 06:28
I'm reopening this because I agree with @Lamborge that it should be possible to set the color of a `View`'s border independently of `View.ColorScheme`.

Coincidentally, I personally discovered it was not possible yesterday. 

I've changed this issue to be of type "Improvement" and milestone == v2 because, as @BDisp notes, the current implementation is working "by design" (but I think the design can be improved). 

Note that in the V2 discussion I used this as an example of something we should re-architect for V2:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/585482/218386476-11b12fd8-eb88-4a4e-8ee6-ab57f0e37cc2.png">

https://github.com/gui-cs/Terminal.Gui/discussions/1940

**Comment by BDisp** [comment] 2023-02-13 20:08
I didn't realized the user want a new feature since he talk about a bug. Sorry @Lamborge for the misunderstanding. I added the feature where the margin frame and the title colors are based on the `Border.BorderBrush` and the `Border.Background` properties. I hope this can satisfy your needs for now.

**Comment by tig** [comment] 2023-02-14 03:38
@Lamborge - how important is this feature to you right now? 

I ask, because the new feature @BDisp added to meet your request requires a complex solution touching a lot of code. THis is because the architecture between `View` and `Border` is complex. In Terminal.Gui v2 we'd like to radically simplify all of this, and I'd rather not have us add more complexity to v1, and instead focus on v2. 

However, if you will use the new feature immediately, I'll accept @BDisp's pull request and merge it into v1 (`develop`). He did a great job on it.

Let us know! Thanks!

**Comment by Lamborge** [comment] 2023-02-14 16:26
> @Lamborge - how important is this feature to you right now?
> 
> I ask, because the new feature @BDisp added to meet your request requires a complex solution touching a lot of code. THis is because the architecture between `View` and `Border` is complex. In Terminal.Gui v2 we'd like to radically simplify all of this, and I'd rather not have us add more complexity to v1, and instead focus on v2.
> 
> However, if you will use the new feature immediately, I'll accept @BDisp's pull request and merge it into v1 (`develop`). He did a great job on it.
> 
> Let us know! Thanks!

well, I don't think this function is very important, but I would like the View structure to be more understandable, and such a simple action as changing the color of the border did not require extra actions

If you want to change the color of the border - just change the color of the border

**Comment by BDisp** [comment] 2023-02-14 16:59
> well, I don't think this function is very important, but I would like the View structure to be more understandable, and such a simple action as changing the color of the border did not require extra actions
> 
Thanks for your feedback. I think now it's better than before because prior the border frame color was always inherit by the view. Now is possible to personalize the border frame color separated from the view `ColorScheme`.
@tig I think this should be merged because it's respect the default values and only change the border color if explicit used by the user.

> If you want to change the color of the border - just change the color of the border

Now you only needed to set the `Border.BorderBrushand` the `Border.Background` to set the foreground and the background, respectively. See on the scenario.

![border-colors-fix](https://user-images.githubusercontent.com/13117724/218804180-136f608c-c253-4a14-876a-6e63a0416256.gif)

**Comment by Lamborge** [comment] 2023-02-14 17:08
> Now you only needed to set the `Border.BorderBrushand` the `Border.Background` to set the foreground and the background, respectively. See on the scenario.

Many thanks for the work done! I would also like to suggest that all the settings of the child Views be inherited from the parent ones. I think this would greatly simplify writing code and clear it of unnecessary repetition.
By type Border child = Border parent

**Comment by BDisp** [comment] 2023-02-14 17:31
> Many thanks for the work done! I would also like to suggest that all the settings of the child Views be inherited from the parent ones. I think this would greatly simplify writing code and clear it of unnecessary repetition.
> By type Border child = Border parent

Or I do not understand very well want you are suggestion but I think you are made some confusing about how the `Border` class work. Only one off them can have `Border` initialized, otherwise the Border doesn't now what border must be handled. e.g. The `Window` and the `FrameView` both have border initialized and their child's are the `ContentView` where others views can be added. For these views added the `Border` class isn't responsible to create border to them. This is a user responsibility to add or not borders to them. Are I'm loosing anything?

**Comment by Lamborge** [comment] 2023-02-14 17:35
I gave the Border class only as an example, in my code I ran into a problem that I need to specify a ColorScheme for each individual Window, including child Window

**Comment by BDisp** [comment] 2023-02-14 17:40
> I gave the Border class only as an example, in my code I ran into a problem that I need to specify a ColorScheme for each individual Window, including child Window

Ah ok, but normally the `Window`'s subviews inherit the `ColorScheme` from the parent. Can you fill a simple code where that isn't working please?

**Comment by Lamborge** [comment] 2023-02-14 17:56
https://github.com/Lamborge/ASCIItism/blob/main/MainWin.cs
https://github.com/Lamborge/ASCIItism/blob/main/MainWin.Designer.cs

in this code BasicWin in MainWin.Designer.cs dont use ColorScheme of MainWin in MainWin.cs
but maybe this is my mistake

**Comment by BDisp** [comment] 2023-02-14 18:07
> https://github.com/Lamborge/ASCIItism/blob/main/MainWin.cs https://github.com/Lamborge/ASCIItism/blob/main/MainWin.Designer.cs
> 
> in this code BasicWin in MainWin.Designer.cs dont use ColorScheme of MainWin in MainWin.cs but maybe this is my mistake

Because you are instantiating as `BasicWindow = new Window()` instead of `BasicWindow = new MainWin()`.

**Comment by Lamborge** [comment] 2023-02-14 18:44
hmm, got it, this solves a lot of problems, can I close the issue?

**Comment by BDisp** [comment] 2023-02-14 18:47
> hmm, got it, this solves a lot of problems, can I close the issue?

I'm glad it works. No because I have a PR that links to this issue. Thanks.

**Closed** 2023-02-25 22:26 UTC
Labels: enhancement
