### ISSUE TITLE
New terminal backend

### ISSUE THREAD

**Issue by migueldeicaza** [gui-cs/Terminal.Gui#370] opened 2020-04-15 04:21 UTC
Dealing with old ncurses, versions compiled without everything is annoying.   Perhaps the time has come to just support the vt100/xterm family of terminals and have a direct driver.

**Comment by tig** [comment] 2020-09-28 20:50
Issues that will be resolved by this:

- https://github.com/migueldeicaza/gui.cs/issues/881
-

**Comment by BDisp** [comment] 2022-08-29 21:00
> Issues that will be resolved by this:
> 
>     * [Modifier key are not fully supported with CursesDriver #881](https://github.com/gui-cs/Terminal.Gui/issues/881)
> 
>     * [The native method "COLOR_PAIRS" does not exist #415](https://github.com/gui-cs/Terminal.Gui/issues/415)

These issue are already closed.

Well, I think the `NetDriver` implemented by @migueldeicaza and enhanced by me, in some way solves part of this, since it'support multi-platform.

**Comment by tig** [comment] 2024-01-19 16:02
Closing as dupe of

- #2610

**Closed by tig** 2024-01-19 16:02 UTC
Labels: enhancement
