### ISSUE TITLE
Application crashes while resizing on Windows 10 Version 22H2

### ISSUE THREAD

**Issue by kacperpikacz** [gui-cs/Terminal.Gui#2714] opened 2023-06-13 23:03 UTC
**Describe the bug**
When resizing the terminal by grabbing a corner or double-clicking on the title bar, the application throws an error. The problem disappears after removing the button.

**To Reproduce**
```
using Terminal.Gui;

namespace Test
{
    public class Program
    {
        static void Main()
        {
            Application.Init();
            var container = new View() { X = Pos.Center(), Y = Pos.Center(), Width = 8, Height = 8, ColorScheme = Colors.Error };
            var button = new Button("Test") { X = Pos.Center(), Y = Pos.Center() };
            container.Add(button);
            Application.Top.Add(container);
            Application.Run();

            return;
        }
    }
}


```

**Screenshots**
![guics](https://github.com/gui-cs/Terminal.Gui/assets/76921244/002366cb-27f8-415a-9b90-92fd506b606f)
![gui2](https://github.com/gui-cs/Terminal.Gui/assets/76921244/178b44a8-102c-47a0-9d06-dbcfaa7e6f6c)

**Desktop:**
 - OS: Windows 10
 - TerminalGui version: 1.12.1

**Comment by kacperpikacz** [comment] 2023-06-14 04:32
**Update**
When you remove `Pos.Center()` from X, Y of the button, the problem also disappear.

**Comment by tznind** [comment] 2023-06-14 07:40
Running this demo I have no issues resizing from borders but if I double click the task bar to maximise then double click the task bar to return to previous size I get the following error:

```
System.ComponentModel.Win32Exception: 'No process is on the other end of the pipe.'
```

Full stack trace is:
```
System.IO.IOException
  HResult=0x800700E9
  Message=No process is on the other end of the pipe.
  Source=System.Console
  StackTrace:
   at System.ConsolePal.WindowsConsoleStream.Write(ReadOnlySpan`1 buffer)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder) in /_/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs:line 330
   at System.IO.StreamWriter.Write(String value) in /_/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs:line 495
   at System.IO.TextWriter.SyncTextWriter.Write(String value) in /_/src/libraries/System.Private.CoreLib/src/System/IO/TextWriter.cs:line 798
   at Terminal.Gui.WindowsDriver.ResizeScreen()
   at Terminal.Gui.WindowsDriver.ChangeWin(Size e)
   at Terminal.Gui.WindowsMainLoop.Terminal.Gui.IMainLoopDriver.MainIteration()
   at Terminal.Gui.MainLoop.MainIteration()
   at Terminal.Gui.Application.RunMainLoopIteration(RunState& state, Boolean wait, Boolean& firstIteration)
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
   at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler)
   at Test.Program.Main() in D:\Repos\deletemeconsole\Program.cs:line 14
```

**Comment by serega404** [comment] 2023-06-14 11:23
I was able to reproduce this error exactly. I also had this problem in my project when I stretched the console on the x-axis very quickly.

```
An exception occurred: CLR/System.ComponentModel.Win32Exception
Unhandled exception of type 'System.ComponentModel.Win32Exception' in Terminal.Gui.dll: 'There are no processes on either end of the pipe.'
    at Terminal.Gui.WindowsConsole.SetConsoleWindow(Int16 cols, Int16 rows)
    in Terminal.Gui.WindowsDriver.ChangeWin(Size e)
    at Terminal.Gui.WindowsMainLoop.Terminal.Gui.IMainLoopDriver.MainIteration()
    in Terminal.Gui.MainLoop.MainIteration()
    in Terminal.Gui.Application.RunMainLoopIteration(RunState& state, Boolean wait, Boolean& firstIteration)
    in Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
    in Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler)
```

**Comment by kacperpikacz** [comment] 2023-06-14 16:35
> Running this demo I have no issues resizing from borders but if I double click the task bar to maximise then double click the task bar to return to previous size I get the following error (sometimes I have to expand/collapse multiple times):
> 
> 
> 
> ```
> 
> System.ComponentModel.Win32Exception: 'No process is on the other end of the pipe.'
> 
> ```
> 
> 
> 
> I can repro in both the vs debugger terminal and powershell.
> 
> 
> 
> Issue seems to also affect v2_develop.
> 
> 
> 
> Full stack trace is:
> 
> ```
> 
> System.IO.IOException
> 
>   HResult=0x800700E9
> 
>   Message=No process is on the other end of the pipe.
> 
>   Source=System.Console
> 
>   StackTrace:
> 
>    at System.ConsolePal.WindowsConsoleStream.Write(ReadOnlySpan`1 buffer)
> 
>    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder) in /_/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs:line 330
> 
>    at System.IO.StreamWriter.Write(String value) in /_/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs:line 495
> 
>    at System.IO.TextWriter.SyncTextWriter.Write(String value) in /_/src/libraries/System.Private.CoreLib/src/System/IO/TextWriter.cs:line 798
> 
>    at Terminal.Gui.WindowsDriver.ResizeScreen()
> 
>    at Terminal.Gui.WindowsDriver.ChangeWin(Size e)
> 
>    at Terminal.Gui.WindowsMainLoop.Terminal.Gui.IMainLoopDriver.MainIteration()
> 
>    at Terminal.Gui.MainLoop.MainIteration()
> 
>    at Terminal.Gui.Application.RunMainLoopIteration(RunState& state, Boolean wait, Boolean& firstIteration)
> 
>    at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
> 
>    at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler)
> 
>    at Test.Program.Main() in D:\Repos\deletemeconsole\Program.cs:line 14
> 
> ```

Before you try to reproduce error by resizing using corners, resize using double clicking 2 times(maximize and back to original size. If app will not crash you can start playing with resizing using grabbing corners fast. In some moment the app will crash.

**Comment by kacperpikacz** [comment] 2023-06-16 07:42
No idea why, but the code below solves the problem.

**WindowsDriver.cs**
```
private void ChangeWin (Size e)
{
	if (!EnableConsoleScrolling) {
		var w = e.Width;
		if (w == cols - 3 && e.Height < rows) {
			w += 3;
		}

//	-	var newSize = WinConsole.SetConsoleWindow (
//	-		(short)Math.Max (w, 16), (short)Math.Max (e.Height, 0));

//	+	var newSize = WinConsole.SetConsoleWindow (
//	+		(short)Math.Max (w - 1, 16), (short)Math.Max (e.Height, 0));


		left = 0;
		top = 0;
		cols = newSize.Width;
		rows = newSize.Height;
		ResizeScreen ();
		UpdateOffScreen ();
		TerminalResized.Invoke ();
	}
}
```

**Comment by tznind** [comment] 2023-06-16 08:05
I think we need to throttle the processing of windows resize events.  I added your change but it seems to result in the window shrinking after resizing (see below).  It does make things more reliable but doesn't eliminate the issue as I was still able to reproduce periodically.

But the more interesting thing for me is just how many consecutive events are going through.  Maybe we need to ignore resize events during resize events? or just handle the first and last?



![throttle](https://github.com/gui-cs/Terminal.Gui/assets/31306100/3a309ba5-3d60-453f-a0b3-c90657027e7d)

**Comment by kacperpikacz** [comment] 2023-06-16 08:23
@tznind In my opinion, it makes no sense to take into account every terminal resizing event. It should be possible to configure how the `Application` behaves when resizing.

**Comment by BDisp** [comment] 2023-06-23 11:17
> @tznind In my opinion, it makes no sense to take into account every terminal resizing event. It should be possible to configure how the `Application` behaves when resizing.

@kacperpikacz you're right. There are two stages where it's needed to avoid the terminal resizing. One on the resize event itself, where can be check for another main loop resize event flag, where if it's true don't processes the prior. Another, more harder to control is when the terminal resizing is already processing the resizing but need to check if it has another process event and cancelling the running one.

**Comment by tznind** [comment] 2023-07-01 14:10
Please can people try with this adjustment of resize polling rate: #2731

**Comment by BDisp** [comment] 2023-07-01 17:09
@kacperpikacz can you confirm if you are using the `Windows 10 Version 22H2`?

**Comment by kacperpikacz** [comment] 2023-07-03 19:22
@BDisp yes, im using 22H2.

**Comment by Decimation** [comment] 2023-07-10 09:50
I have the exact same problem.

**Comment by moonphone** [comment] 2023-07-10 12:13
For me, it's just in case of resizing to normal size via the Windows native button (window top right corner, the mid button).
If i click it after the window got maximized...
![image](https://github.com/gui-cs/Terminal.Gui/assets/104312523/3464d19a-b780-4f36-b9db-33812f8c9bdb)

Win32Exception: No Process on the end of the pipe

**Comment by BDisp** [comment] 2023-07-10 12:23
This problem has to be subjected to https://github.com/microsoft/dotnet but I haven't had a chance yet. I would like someone to be available to submit it, please.

**Comment by kacperpikacz** [comment] 2023-07-10 17:50
MS Pipe leakage

**Comment by tig** [comment] 2024-01-19 16:49
Dupe of 

- #2856
 
Closing.

**Closed by tig** 2024-01-19 16:49 UTC
Labels: bug
