### ISSUE TITLE
Issues with Application.Top being null if dispose is called on the window object

### ISSUE THREAD

**Issue by FreddieMercurial** [gui-cs/Terminal.Gui#1611] opened 2022-02-21 20:13 UTC
https://github.com/migueldeicaza/gui.cs/blob/1557f7a71e3dd4a0163d08375e2788dd687a7cba/Terminal.Gui/Core/View.cs#L366

![image](https://user-images.githubusercontent.com/3766240/155020618-a533c3a2-aac3-4bc6-ba19-467ae419c4af.png)

This line does it the correct way
https://github.com/migueldeicaza/gui.cs/blob/1557f7a71e3dd4a0163d08375e2788dd687a7cba/Terminal.Gui/Core/View.cs#L359

**Comment by BDisp** [comment] 2022-02-21 21:12
I did not understand the comparison you did. It seems you are disposing an object that was already disposed.

**Comment by FreddieMercurial** [comment] 2022-02-22 02:57
_window was not itself previously disposed- but encounters the error I pointed out trying to read Application.Top.Focused when .Top is null

**Comment by tznind** [comment] 2022-02-22 08:32
Thanks for identifying an issue and the fix.  Are you able to write a unit test that shows the issue? Something like:

```csharp
[Fact]
[AutoInitShutdown]
public void WindowDispose_FocusProblem()
{
    // TODO: Add other statements here to reproduce your issue
    new Window().Dispose();
}
```

**Comment by BDisp** [comment] 2022-02-22 14:17
Thanks for reporting this. I already found a bug where a view that has focus and setting `CanFocus` to false is setting `HasFocus` to `false` and to `true` again. I'll submit a PR with a fix.
Nonetheless, I couldn't reproduce the disposing focus issue. Can you provide more information about how you get the exception, or test with the fix I'll provide to check if you still getting the exception again.

**Comment by FreddieMercurial** [comment] 2022-03-04 21:40
Sorry for being slow on the response! Glad it wasn't PEBKAC after all!
Will give it a run!

**Comment by tig** [comment] 2022-08-04 16:09
Closing as not-repo.

**Closed by tig** 2022-08-04 16:09 UTC
Labels: bug
