### ISSUE TITLE
Windows Terminal - Last line of app is not cleared when exiting

### ISSUE THREAD

**Issue by ThomasNieto** [gui-cs/Terminal.Gui#2634] opened 2023-05-16 03:14 UTC
**Describe the bug**
In the Windows Terminal the status menu sticks around after quitting.

Version: 1.16.10261.0

**To Reproduce**
Open UI catalog and then quit. The status menu will stick around.

**Expected behavior**
Status menu goes away after quitting

**Screenshots**
![image](https://github.com/gui-cs/Terminal.Gui/assets/38873752/f714e9eb-9d7f-4891-8189-1e49ff28d254)

**Comment by BDisp** [comment] 2023-05-16 10:35
That also happens to me with  the `WindowsDriver` but only for a second and then disappear.

**Comment by tig** [comment] 2023-07-20 12:31
FWIW, I don't always see this because I use a mullti-line `oh-my-posh` prompt...

**Comment by tig** [comment] 2023-07-20 12:34
It does not reproduce on ConEmu.

**Comment by tig** [comment] 2023-08-03 22:34
I'm reopening this as my fix does not seem to actually work. See https://github.com/gui-cs/F7History/issues/13

**Comment by tig** [comment] 2023-10-17 17:41
Now fixed.

**Closed by tig** 2023-10-17 17:41 UTC
Labels: bug, v1

**Comment by jkav58** [comment] 2023-10-17 17:44
> Now fixed.

When will we see the fix?

**Comment by tig** [comment] 2023-10-17 22:46
> > Now fixed.
> 
> When will we see the fix?

This is fixed in `main` and thus 1.14 which is the current release on Nuget. Here's the latest ocgv, built using `main`:

![9e5mO8b 1](https://github.com/gui-cs/Terminal.Gui/assets/585482/5cdb230a-95ee-46f0-9098-096d5ef4430b)

The PS team needs to do a new release of ocgv...
