### ISSUE TITLE
TextField and TextView not showing cursor (invisible cursor)

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3891] opened 2024-12-21 10:09 UTC
**Describe the bug**
When entering text view there is no change to show cursor.

**To Reproduce**
1. Run UICatalog
2. Go to Text Input Controls
3. Click into text editor and type
4. See error (no cursor)

**Expected behavior**
Entering view should cause cursor to become visible.

**Screenshots**
![no-cursor-text-view](https://github.com/user-attachments/assets/7cd039bf-9c1c-4c9b-969e-2f3867dccdb7)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Set Project & Milestone**
If you have access, please don't forget to set the right Project and Milestone.

**Comment by tig** [comment] 2024-12-21 13:41
Dupe of #3881

**Closed** 2024-12-21 13:41 UTC
Labels: bug, v2
