### ISSUE TITLE
Memory leaks on Toplevel, Responder, and LineCanvas

### ISSUE THREAD

**Issue by famblard86** [gui-cs/Terminal.Gui#2870] opened 2023-09-30 22:20 UTC
**Describe the bug**
Objects never gc. 

**To Reproduce**
1. Run UICatalog
2. Go to 'Dialogs Scenario'
3. Click on 'Show Dialog'
4. Leave Dialog
5. Run step 3 & 4 x time
6. Take memory snapshoot

You see in memory Terminal.Gui.Dialog x time you click on Show Dialog

Just for tests I have fixed it locally by modifying Toplevel Dispose method like this to append -=
 ```
protected override void Dispose (bool disposing)
{
	Application.GrabbingMouse -= Application_GrabbingMouse;
	Application.UnGrabbingMouse -= Application_UnGrabbingMouse;

	_dragPosition = null;
	base.Dispose (disposing);
}
```
and Responder Dipose methode to remove in static List instance
```
protected virtual void Dispose (bool disposing)
{
	if (!disposedValue) {
		if (disposing) {
			// TODO: dispose managed state (managed objects)
		}

		// TODO: free unmanaged resources (unmanaged objects) and override finalizer
		// TODO: set large fields to null
		disposedValue = true;
		Instances.Remove (this);
	}
}
```
I don't know the project so i'm not sure if it's the good place to do this.

I didn't search how to fix it but it seems LineCanvas never unsubscribe `ConfigurationManager.Applied += ConfigurationManager_Applied;`

**Comment by BDisp** [comment] 2023-09-30 23:08
Thanks for reporting this. I really have realized a long time that when I consecutively opening and closing the same scenario the delay increase dramatically. Maybe in the `Responder` is the better place to unsubscribe all the events used by the view on disposing.

**Comment by tig** [comment] 2023-10-02 01:44
Yes, thanks for reporting!

Based on this I dug in....

The fix to Application and Responder are right on, but are not the cause of the weird behavior @BDisp  and I have both seen... something else is still there, I think.

I found the issue with `LineCanvas` as well:

- I had old code where I overrode `View.LineCanvas` in `Frame` and this was causing `LineCanvas` instances to be created an not cleaned up for every Frame object created. 

I will prepare a set of PRs (one for V1 and one for V2) that addresses these.

Thanks again!

**Closed** 2023-10-06 04:24 UTC
Labels: bug, v2
