### ISSUE TITLE
`Dim.Auto (Content)` is broken if subviews use `Pos.Center` etc...

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3567] opened 2024-06-25 18:25 UTC
![WindowsTerminal_DGKWnv3Fhi](https://github.com/gui-cs/Terminal.Gui/assets/13117724/373e6472-3968-49e3-b67f-53f90783a741)

**Comment by tig** [comment] 2024-06-25 20:14
Yes. 

I'm working on it.

**Comment by tig** [comment] 2024-07-12 17:52
Dupe of #3499

**Closed by tig** 2024-07-12 17:52 UTC
Labels: bug, v2

**Comment by dodexahedron** [comment] 2024-07-12 23:55
> Dupe of #3499

Ok, I wasn't going crazy then haha. I _knew_ I had seen this brought up before. 😅
