### ISSUE TITLE
BackgroundWorker Collection scenario is broken.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2162] opened 2022-11-03 00:36 UTC
Some changes in the `UICatalog` caused it to broken,

**Comment by tig** [comment] 2022-11-03 01:51
Digging into this, I think UI Catalog is correct.

I think the bug is actually here:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/585482/199633908-c7ca87dc-27e4-485e-ae66-b18bcd346ba1.png">

This check for multiple Mdi containers should see if `MdiTop != topLevel`:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/585482/199633963-d49b72b8-d8cd-4363-8c55-84162b2cccc2.png">

With this change, and `BackgroundWorkerCollection.cs` changed thusly:

```csharp
namespace UICatalog.Scenarios {
	[ScenarioMetadata (Name: "BackgroundWorker Collection", Description: "A persisting multi Toplevel BackgroundWorker threading")]
	[ScenarioCategory ("Threading")]
	[ScenarioCategory ("Top Level Windows")]
	[ScenarioCategory ("Dialogs")]
	[ScenarioCategory ("Controls")]
	public class BackgroundWorkerCollection : Scenario {
		public override void Init (Toplevel top, ColorScheme colorScheme)
		{
		}

		public override void Run ()
		{
			Application.Run<MdiMain> ();
		}

```

It all works correctly.

@BDisp what are your thoughts?

**Comment by BDisp** [comment] 2022-11-03 07:26
But also has another issue when you start a work and try to move the window by mouse. Sometimes it draw two menu bars.

**Comment by tig** [comment] 2022-11-03 12:32
I can repo. Are you sure it didn't do this before?

<img width="605" alt="image" src="https://user-images.githubusercontent.com/585482/199721290-38fd9772-4ae8-4dc8-9675-a18e083ce466.png">

**Comment by BDisp** [comment] 2022-11-03 12:45
> I can repo. Are you sure it didn't do this before?

I don't think so.

In the `scenario.Init (Application.Top, _colorScheme);` the parameter `Application.Top` now will be always null. I think this method shouldn't have any parameters, because if the user don't use it he can initialize a customized toplevel, by overridden the `Run` method without code.. Doing in the `scenario.Run ();` is a waste of resources because we need to `Dispose` before recreate a new one.
Because `Application.Top` is create by calling the `Application.Init()` and it's not already added to the topLevels, is more accreted to call `Top.Dispose();` before set `Top = null;` in the ResetState method, to ensure that the `Top` is disposed in the case it wasn't added to the toplevel, because the `foreach (var t in toplevels)` will be empty.

**Comment by tig** [comment] 2022-11-03 13:09
> > I can repo. Are you sure it didn't do this before?
> 
> I don't think so.


I just reverted to before I merged the UI Catalog refactoring and this issue still exits.

Go back to your `vkpacket-fix4` branch, which was merged before I did the UI Cat work and you'll see this double menu thing reproduces there.

I then went back to v1.82 and it repros there too. So this has nothing to with my UI Cat changes or THIS PR.

> 
> In the `scenario.Init (Application.Top, _colorScheme);` the parameter `Application.Top` now will be always null. I think this method shouldn't have any parameters, because if the user don't use it he can initialize a customized toplevel, by overridden the `Run` method without code.. 

I completely agree! I will do another PR to simplify this (I had considered it before but then forgot).

> Doing in the `scenario.Run ();` is a waste of resources because we need to `Dispose` before recreate a new one. Because `Application.Top` is created by calling the `Application.Init()` and it's not already added to the topLevels, is more accurate to call `Top.Dispose();` before set `Top = null;` in the `ResetState` method, to ensure that the `Top` is disposed in the case it wasn't added to the `toplevels`, because the `foreach (var t in toplevels)` will be empty.

I think this is right, but I need to look more closely. BackgroundWorker Collection is the only Scenario that uses Run<T>(). So it's a great test case for all of this. 

I suggest we close THIS PR and move the discussion to #520, which is where the root cause is. Ok?

**Comment by BDisp** [comment] 2022-11-03 13:21
> I suggest we close THIS PR and move the discussion to #520, which is where the root cause is. Ok?

I agree. Thanks.

**Comment by BDisp** [comment] 2022-11-05 18:48
@tig in the `UICatalog.cs` I think doesn't any sense to call `scenario.Init (Application.Top, _colorScheme);` without call `Application.Init ();` before, otherwise the `Application.Top` will be always null because `Application.Shutdown` was called before.

![imagem](https://user-images.githubusercontent.com/13117724/200135874-202922dc-9108-48b1-8123-eb6c2d4f4120.png)

**Comment by tig** [comment] 2022-11-05 22:36
> @tig in the `UICatalog.cs` I think doesn't any sense to call `scenario.Init (Application.Top, _colorScheme);` without call `Application.Init ();` before, otherwise the `Application.Top` will be always null because `Application.Shutdown` was called before.
> 

See new code:

```cs
			Scenario scenario;
			while ((scenario = RunUICatalogTopLevel ()) != null) {
				VerifyObjectsWereDisposed ();
				scenario.Init (_colorScheme);
				scenario.Setup ();
				scenario.Run ();

				// This call to Application.Shutdown brackets the Application.Init call
				// made by Scenario.Init() above
				Application.Shutdown ();

				VerifyObjectsWereDisposed ();
			}
			VerifyObjectsWereDisposed ();
```

**Comment by BDisp** [comment] 2022-11-05 22:53
> scenario.Init (_colorScheme);

I really have seen this before.

**Comment by tig** [comment] 2022-11-05 23:55
> > scenario.Init (_colorScheme);
> 
> I really have seen this before.

what do you mean?

**Comment by BDisp** [comment] 2022-11-05 23:57
> what do you mean?

Without the top parameter :-)

**Comment by tig** [comment] 2022-11-06 00:47
> > what do you mean?
> 
> Without the top parameter :-)

It was your suggestion to nuke it. Are you not happy I did so? I think I'm missing something you are trying to say.

**Comment by BDisp** [comment] 2022-11-06 01:01
> It was your suggestion to nuke it. Are you not happy I did so? I think I'm missing something you are trying to say.

Not really believe me. I never liked the `Top` property too. The colorscheme parameter is important because it allow to change the color scheme on the menu and we test in the scenarios, if the color scheme isn't changing on the scenario, of course. So, in the override `Init` we have the option of hack another initialization. If not used then the `base.Init` will be executed.

**Closed** 2022-11-11 18:50 UTC
Labels: bug
