### ISSUE TITLE
Menu does not appear when invoked from hotkey

### ISSUE THREAD

**Issue by SixOThree** [gui-cs/Terminal.Gui#2186] opened 2022-11-05 20:09 UTC
**Describe the bug**
Following the documentation for [TopLevel Views](https://gui-cs.github.io/Terminal.Gui/articles/overview.html#toplevel-views), when the MenuBar is invoked using a hotkey Alt+F, the menu does not appear. 

**To Reproduce**
Use only code from the Terminal.Gui API Overview [TopLevel Views](https://gui-cs.github.io/Terminal.Gui/articles/overview.html#toplevel-views). Invoke the MenuBar using Alt+F, the menu will not appear. 

If you invoke menu and then use the arrow keys. it will appear. If you click MenuBar with the mouse, the menu will appear. If you remove the TextView from the example code, the menu will appear correctly.

**Expected behavior**
Documentation should provide an example that allows menubar to appear correctly.

**Screenshots**
Issue:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/296042/200138935-f1235e6a-c109-40c3-b553-f7efa189b673.png">
Expected:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/296042/200138962-1f802253-b380-41db-b91d-eacbcf111bf5.png">

**Desktop (please complete the following information):**
Windows Terminal Version: 1.15.2875.0

**Additional context**
I am new to this project and do not know if the issue is related to the documentation, the MenuBar, or the TextView.

**Comment by BDisp** [comment] 2022-11-05 20:17
It's not a bug. Given the `TextView` is focused and `Alt+F` is also used for move the cursor by word forward it will not open the menu bar.

**Comment by tznind** [comment] 2022-11-05 20:31
To elaborate on @BDisp point: Alt+F will activate menu bar but priority is given to the most focused control (i.e. `TextView`).

If you like you can prevent this behavior by clearing the Alt+F shortcut from the `TextView`:

```csharp
textView.ClearKeybinding(Key.AltMask | Key.F);
```
Alternatively you can use the F9 key to open menu.

**Comment by tig** [comment] 2024-08-06 15:52
Closing. This will be addressed in #2975.

**Closed by tig** 2024-08-06 15:52 UTC
Labels: docs
