### ISSUE TITLE
Button clicked event is raised even with mouse button pressed on another view.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3392] opened 2024-04-09 08:26 UTC
**Describe the bug**
The clicked event should only occur if the view mouse button was pressed and released on the same view, not at same same coordinates as it happened previously. The terminal mouse API should raise the clicked event but is View responsibility to send it to the valid view. The terminal mouse API don't know about the View class and only send the clicked event because a Pressed+Release mouse button occurred.

**To Reproduce**
1. Go to 'UICatalog.'
2. Open the 'Buttons' scenario
3. Check if the first 'TextField' is selected and press the mouse on it
4. Kept the mouse pressed and move the mouse to any of the buttons and release the mouse
5. The Dialog is opened even the mouse button pressed and released wasn't in that view
6. This doesn't happens if you press the mouse on a Button and release it on another Button, which is good

**Expected behavior**
The clicked event should not occurred.

**Comment by BDisp** [comment] 2024-04-09 11:37
This code isn't totally correct. The `_mouseEnteredView` which in my opinion is the latest that ran the `OnMouseEnter` event isn't updated if the `return` is called before any chance of it being setting in the case of the current view is different.

![image](https://github.com/gui-cs/Terminal.Gui/assets/13117724/3c39d5b8-9d3f-4749-9625-608e6075f957)

The line `_mouseEnteredView?.NewMouseLeaveEvent (mouseEvent);` may contain an outdated view.

**Comment by BDisp** [comment] 2024-04-09 11:42
Another issue is when the mouse button is pressed on a Button and kept pressed move to another Button and release the mouse. The clicked event isn't executed and this is good, but if you press and release the mouse in the second button nothing happen. Only on the second mouse  press and release the clicked event is processed.

**Comment by tig** [comment] 2024-04-09 12:13
> **Describe the bug** The clicked event should only occur if the view mouse button was pressed and released on the same view, not at same same coordinates as it happened previously. The terminal mouse API should raise the clicked event but is View responsibility to send it to the valid view. The terminal mouse API don't know about the View class and only send the clicked event because a Pressed+Release mouse button occurred.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'UICatalog.'
> 2. Open the 'Buttons' scenario
> 3. Check if the first 'TextField' is selected and press the mouse on it
> 4. Kept the mouse pressed and move the mouse to any of the buttons and release the mouse
> 5. The Dialog is opened even the mouse button pressed and released wasn't in that view
> 6. This doesn't happens if you press the mouse on a Button and release it on another Button, which is good
> 
> **Expected behavior** The clicked event should not occurred.

The cause is:

- #3312 

Another way to reproduce it:

1. Run UI Catalog
2. Ctrl-A to open about box
3. Press and hold mouse outside of about box
4. Drag over about box

Expected:
- Nothing happens

Actual:
- About box moves

![XDOIDNj 1](https://github.com/gui-cs/Terminal.Gui/assets/585482/4c5b795a-b7e0-4261-99d8-eba2685fb5ff)

Closing as duplicate.

**Closed by tig** 2024-04-09 12:13 UTC
