### ISSUE TITLE
Checkbox and radio buttons symbols on 'old' Linux TTY ?

### ISSUE THREAD

**Issue by lzanoni-stm** [gui-cs/Terminal.Gui#1774] opened 2022-06-07 10:09 UTC
Hello,

is there a way to have the checked/unckecked marks and (un)selected radio buttons displayed correctly on plain Linux TTY ?
I also need to display the fours arrow symbols (U2190-U2193).
My targets are Centos7 and Ubuntu20+

I tested the UICatalog with and without -usc, and the 'Character Map' demo is also badly rendered (most char are a rectangular bar).
It works fine under Windows; also by SSH-ing (from a Windows terminal) and in WSL.

Perhaps by setting another TERM variable, selecting another 'font', or even by using another frame-buffer?
I tested 'tmux' without success.

Is there a fallback system to use X checkmark instead of glyphs ?

**Comment by lzanoni-stm** [comment] 2022-06-07 10:56
TERM indeed is 'linux'.
I tried with 'xterm-256color', but no change. I will try on another linux distro.
Thanks for the suggestion about changing the symbols, interesting workaround.

**Comment by BDisp** [comment] 2022-06-07 10:59
> I tried with 'xterm-256color', but no change.

Did you reboot after the change?

**Comment by tznind** [comment] 2022-06-07 11:18
> Did you reboot after the change?

It shouldn't require reboot.  The TERM value is a workaround which sometimes works and sometimes doesn't (helps with Guacamole and PuTTY see [this discussion](https://github.com/migueldeicaza/gui.cs/discussions/1455))  But it mostly seems to fix color problems anyway not unsupported symbols. Just thought I would suggest it just incase.

I have also noticed PowerShell on my Windows 10 machine sometimes not supporting the checkbox symbol.  I think I have 2 shortcuts on my start menu one which does and one which doesn't so I must have 2 different versions installed.

My feeling is that this is a missing font or just that the installed/used font (of the terminal) doesn't have that symbol mapped.  Not sure how to detect the situation at runtime especially since its going to be down to the terminal itself not the running app.

I wonder how widespread the issue is... if there are a lot of environments that don't support our default unicode symbol  for checked/unchecked then we could look into changing them @tig  / @BDisp ? 

ncurses already looks at the $TERM variable when deciding on color setup so might be that we could use that for insight into likely unicode rune support but its not my area of knowledge really.

**Comment by tig** [comment] 2022-06-08 20:00
> My feeling is that this is a missing font or just that the installed/used font (of the terminal) doesn't have that symbol mapped. Not sure how to detect the situation at runtime especially since its going to be down to the terminal itself not the running app.
> 
> I wonder how widespread the issue is... if there are a lot of environments that don't support our default unicode symbol for checked/unchecked then we could look into changing them @tig / @BDisp ?
> 
> ncurses already looks at the $TERM variable when deciding on color setup so might be that we could use that for insight into likely unicode rune support but its not my area of knowledge really.

Based on this thread, I don't see enough info to know that this wasn't a font issue. 

I spent a ton of time trying to test that the currently glyphs work broadly. But I agree it is possible they don't in some scenarios. 

@lzanoni-stm, can you please confirm what font is being used where the glyphs render incorrectly?

**Comment by tig** [comment] 2022-08-04 16:13
Closing as not-repo.

**Closed by tig** 2022-08-04 16:13 UTC
Labels: bug
