### ISSUE TITLE
Nullable bool Checked for Menu and CheckBox.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2306] opened 2023-01-25 14:27 UTC
**Is your feature request related to a problem? Please describe.**
It's a bit frustrated when we are forced to create a `enum` or a `RadioGroup` to only use 3 options when we can use a nullable bool property.

**Describe the solution you'd like**
The feature of having a `Checked` property with 3 states of a nullable bool value (`null`, `true` and `false`).

**Describe alternatives you've considered**
I considered a workaround by the creation of the properties `AllowsNullChecked` and `NullChecked`, but the simple `get/set` of the `Checked` property will imply a very complexity way to get or set whatever is null, true or false. So, the ensured way to do this is by changing the `Checked` property to a nullable bool (`public bool? Checked`).

**Additional context**
To go ahead with this feature will cause a breaking change on the API and I only go forward with this if the effort and consequences are worthwhile. @tig and @tznind I only starting this if you both agreement.

**Comment by tig** [comment] 2023-01-28 10:00
I think we should revamp the entire api to make use of nullable with v2.0 (because 2.0 allows us to make breaking api changes).

**Comment by tig** [comment] 2023-02-28 02:02
Dupe of #1482

**Closed by tig** 2023-02-28 02:02 UTC
Labels: enhancement
