### ISSUE TITLE
Menu hints in StatusBar

### ISSUE THREAD

**Issue by Slesa** [gui-cs/Terminal.Gui#191] opened 2019-05-03 20:46 UTC
To give an example how to use the messaging in a may existing StatusBar control: in theory, each menu item has a short message explaining what it will do, which would be displayed each time the menu item is hovered.

**Comment by tig** [comment] 2024-01-19 15:59
Closing as dupe of 

- #3076

**Closed by tig** 2024-01-19 15:59 UTC
Labels: enhancement
