### ISSUE TITLE
Mouse does not work with GPM (on Raspbian)

### ISSUE THREAD

**Issue by ArtemKiyashko** [gui-cs/Terminal.Gui#1697] opened 2022-05-06 22:02 UTC
I have a LCD touch screen connected to Raspberry PI with only terminal (Raspberry Pi OS Lite) and mouse events doesn't work there.  For example i cannot switch tabs in tab view or click buttons, etc.

GPM module (General Purpose Mouse) working well in linux terminal (and Raspbian OS). But it does not triggering mouse events in Terminal.Gui. Would be perfect to have its support as well.

Currently i have to attach keyboard to work with terminal app using Teminal.Gui

**Comment by tznind** [comment] 2022-05-07 07:55
Hey thanks for bringing this up.  Are you able to run the 'Mouse' Scenario in UICatalog? when you do do you get any mouse events reported at all with the touchscreen?

My linux laptop has a touch screen and it works (kinda).  To produce a click you have to tap the screen quite precisely but it does work.

![mouse-events](https://user-images.githubusercontent.com/31306100/167244806-751301fd-3773-4949-9a79-63d9986a9c4b.jpg)

For linux gui.cs uses ncurses library so it is possible that it doesn't support GPM or that a dependency is missing or something.  I did an internet search for 'ncurses GPM touchscreen' and there were certainly other people having this issue.

**Comment by ArtemKiyashko** [comment] 2022-05-07 08:27
Hi, i build UICatalog with parameters:
`dotnet publish .\UICatalog.csproj --self-contained -r linux-arm -f net6.0 -c Release`
Just for reference.

But result is not as expected. First of all some issues with colors. By default it running with black text on black background, so i have to swith theme color using hot-keys (and it works) But ok, its not my case.

Regarding mouse events: Mouse scenario does not register any event if i tap on screen or moving mouse pointer or clicking. But it reporting some events when i switching theme color with hot key :-)
I attaching couple of screenshots (these click events registered on after switching theme color, but not when i clicking the mouse). Hope it can help
![photo_2022-05-07_10-17-56 (2)](https://user-images.githubusercontent.com/32637427/167245952-e941776b-843d-4516-9513-2246ce5fe5b4.jpg)
![photo_2022-05-07_10-17-56](https://user-images.githubusercontent.com/32637427/167245953-a6b4a479-3e3e-416d-a0ba-e0926e5de140.jpg)

**Comment by tznind** [comment] 2022-05-07 09:12
What do you get when you type 'echo $TERM' at the console? If you set this environment variable to 'xterm-256color' does it change any of the behaviors?

Also would be good to know if running with `-usc` changes anything?

**Comment by ArtemKiyashko** [comment] 2022-05-07 09:59
When run `echo $TERM` i get just `linux`
![photo_2022-05-07_11-56-41](https://user-images.githubusercontent.com/32637427/167249340-66845a27-d5ec-44fb-be0e-8370d81fd4d7.jpg)

- Without changing environment variable and just run UICatalog with -usc flags fix an issue with colors
- After changing TERM to xterm-256color i can run UICatalog without additional flags and there is everything fine with colors now

Attaching few photos to demostrate.
![photo_2022-05-07_11-55-50](https://user-images.githubusercontent.com/32637427/167249316-5b9abc7a-9a8a-45ba-ba0b-a613a3f8807d.jpg)
![photo_2022-05-07_11-55-49](https://user-images.githubusercontent.com/32637427/167249330-ef6c9067-78aa-4182-b408-1739433336fa.jpg)


Mouse events still doesnt work and i found 1 more behavior. I cannot move mouse pointer below and to the right the position on this photo (looks like some invisible border)
![photo_2022-05-07_11-55-50 (2)](https://user-images.githubusercontent.com/32637427/167249298-3ec2b631-a25b-4bee-84cd-23e42c9a7004.jpg)

**Comment by ArtemKiyashko** [comment] 2022-05-07 10:15
Here is small video with mouse scenario:
https://user-images.githubusercontent.com/32637427/167249950-f06a9213-0273-4e68-b7a9-35e45453166a.MOV

**Comment by tznind** [comment] 2022-05-07 11:14
Thanks for going into the detail on this.  I'm not sure theres much I can do to help but at least the colors and keyboard are working.  I do have a Raspberry Pi in one of my drawers so will try to have an explore at some point.  It is strange that even a usb mouse does not register.

**Comment by BDisp** [comment] 2022-05-07 11:37
I can't help because I don't have a `Raspberry Pi`, sorry. But I notice that the more recent `Linux` versions, like the `Debian 11.2.0` and the `Ubuntu 22.04`, using `CursesDriver`, the mouse events are messed by always repeating the last events on a mouse move. So, in simple mouse move `CursesDriver` is getting button click, double click or whatever wrong event.

**Comment by ArtemKiyashko** [comment] 2022-05-07 11:45
No problems gents, using mouse in linux terminal definitely not a 'kill feature' :-) Especially if i can use a keyboard. Just wanted to have some touch-control in my app, but its not critical. Anyway thanks for support.

**Comment by tig** [comment] 2022-05-07 14:24
I'm curious about what your app does.

**Comment by ArtemKiyashko** [comment] 2022-05-07 16:05
@tig it has 2 tabs. first with telemetry from some sensors, second with data from custom ILogger implementation

https://user-images.githubusercontent.com/32637427/167262419-d4004609-bc20-4809-ac9a-dd18642f6cb0.MOV

So i wanted to switch the tabs using touchscreen if need.

**Comment by tig** [comment] 2022-05-07 16:50
That's awesome. 

I am going to close this Issue as it appears this is not a bug in Terminal.Gui but in GPM or some dependent component. If you think I'm incorrect in this, please feel free to re-open it.

**Comment by ArtemKiyashko** [comment] 2022-05-07 16:55
@tig but mouse working well in other apps, for example in `htop` on same RPI with same mouse and same gpm i can click on buttons with no issues

**Comment by tznind** [comment] 2022-07-01 16:25
So I got around to setting up my Rasberry Pi and connecting up the touchscreen case.  I installed dotnet sdk and cloned Terminal.Gui and there touchscreen seems to be working fine in the GUI OS:

https://www.youtube.com/watch?v=H17Vck6w4_c

Are you running a console only OS? how would I go about recreating your software setup?

**Comment by ArtemKiyashko** [comment] 2022-07-05 07:52
@tznind hi there, sorry for long response i lost access to my github for a while =)

Well yes, i`m using console-only version of raspbian (Raspberry Pi OS Lite). I suppose this is important difference as with desktop GUI everything working fine.
I assume this issue can appear due to some 'missing' component in console version. But i dont know what exactly missing. 
I also did additional test on another, clean PI with same OS and up-to-date packages (e.g. apt update && upgrade) - and it is reproducing (i cannot click any element in Terminal.Gui)
Video of another RPI test:

https://user-images.githubusercontent.com/32637427/177277847-867675b9-6da5-41f4-9a9c-e5808c3a55e5.MOV

**Comment by tznind** [comment] 2022-07-07 18:02
Ok! I have managed to install Raspberry Pi OS Lite and get dotnet sdk on and building/running UICatalog.

I installed GPM and confirmed that it is not generating any input either with the Curses driver or with NetDriver (`-usc`).

I also installed w3m the TUI web browser and note that GPM doesn't work with that either.  **What TUI applications are you using that do support GPM? (so I can test)**

There are a couple of threads about ncurses/GPM interoperability that could be relevant:

- https://bbs.archlinux.org/viewtopic.php?id=225660
- https://forums.gentoo.org/viewtopic-t-1062884-start-0.html

This is as much progress as I can make for now, I will take another shot at this next week since its quite interesting area.  I want to see if I can SSH into the pi and see if mouse works over that at all.

**Comment by ArtemKiyashko** [comment] 2022-07-08 07:00
@tznind yep, mouse working in `htop` as well as through SSH in any terminal app (including UICatalog). Just cheked in Windows Terminal ->SSH to PI
![image](https://user-images.githubusercontent.com/32637427/177935397-e4040458-2766-476a-9597-cf5f51de6130.png)

**Comment by tznind** [comment] 2022-07-08 07:12
When I use htop I can see that it is responding but it is not detecting the location of clicks.  Instead the selection moves to where the GPM drag ends.  It looks like GPM creates a selection over an area and when you release the selection `htop` detects that release as a click. 

I took a video here, notice that its not moving the selection to where my finger actually clicks.  Also it doesn't respond at all to taps (only drags):
https://youtu.be/CpmEqAjKJps

Is this the behavior you have with the touchscreen too? 

> Just cheked in Windows Terminal ->SSH to PI
What was the result? Does the mouse do anything in Terminal.Gui via SSH to the Pi? (with or without GPM enabled).

**Comment by tznind** [comment] 2022-07-08 07:29
Ok so I ran `printf '\033[?1000h'` and then `cat` as described in this article: https://www.reddit.com/r/linux/comments/4f75u5/how_does_htop_gets_my_mouse_input_via_ssh/

Now I can see the console input for cursor keys (e.g. `^[[D^` ) but I see no input from mouse (even with GPM running). 

It is these control codes that Terminal.Gui is subscribing to I think so probably what we need is a way to get GPM to pipe its mouse events to stdin like a regular keyboard event does?

**Comment by tznind** [comment] 2022-07-08 07:31
These threads look relevant:
- https://github.com/telmich/gpm/pull/4
- https://github.com/telmich/gpm/issues/29

**Comment by ArtemKiyashko** [comment] 2022-07-08 08:10
yeah, that could be the case. But answer looks not really promising :)
https://github.com/telmich/gpm/issues/29#issuecomment-423777459

**Comment by tznind** [comment] 2022-07-08 20:09
This looks like a promising start on the issue, even references the GPM issue above.  Might be worth a shot? I'm away at the moment so can't try it but might give it a shot next week some time:

https://codeberg.org/scy/conmaus

**Comment by ArtemKiyashko** [comment] 2022-07-09 13:33
@tznind okay i would call it: partial success =)
Here is few tests:
1. Mouse + UICatalog + conmaus - everything fine! Can see the cursor, can click buttons, etc:

https://user-images.githubusercontent.com/32637427/178107951-5475d2c3-de72-4053-b5c7-01d60d592aa1.mp4


2. Touch screen + UICatalog + conmaus - conmaus crashing with following error:
![conmaus_error](https://user-images.githubusercontent.com/32637427/178107907-d2d9a434-36b0-44ae-b9f9-40d75f316e9e.png)

3. Touch screen + My App + conmaus - conmaus crash as above
4. Mouse + My App + conmaus - no reactions for a clicks, but can see cursor

**Comment by ArtemKiyashko** [comment] 2022-07-17 20:04
For those who is looking for *easy* solution. I created a [PR](https://codeberg.org/scy/conmaus/pulls/1) within [Conmaus](https://codeberg.org/scy/conmaus) repo.

Tested on my Raspberry PI OS Lite **without GPM installed**

https://user-images.githubusercontent.com/32637427/179422843-f3b3b95d-7d3f-4d83-8370-3afa54306a31.mp4

**Comment by tig** [comment] 2022-08-04 16:12
Closing as this is external (I believe).

**Closed by tig** 2022-08-04 16:12 UTC
Labels: bug, Linux
