### ISSUE TITLE
Using emoji

### ISSUE THREAD

**Issue by ChristopheI** [gui-cs/Terminal.Gui#3670] opened 2024-08-19 15:06 UTC
I'm trying this great repository (v 2.0.0-v2-develop.2169) but I can't managed emoji display ...

I previously checked "Unicode" scenario and even in this one I can't display this emoji: 👨

I tried with a little sample - cf. below
I'm using Windows and Visual Studio Enterprise. 

In the TestWindow, the emoji is not well displayed.
Just after,  using Console.WriteLine(), it's well displayed.

I guess I missed something but I don't know what.

Thank in advance

Code used:
```
internal class TestWindow: Window
{
    public TestWindow()
    {
        var str = char.ConvertFromUtf32(0x0001f4fa); // => 👨

        Label lbl1 = new()
        {
            X = 1,
            Y = 1,
            Text = str,
            Width = Dim.Fill()
        };

        Add(lbl1);

        Height = Dim.Fill();
        Width = Dim.Fill();
    }
}

Console.OutputEncoding = Encoding.Default;
Application.Run<TestWindow>().Dispose(); // <= Here the Emoji is not well displayed

var str = char.ConvertFromUtf32(0x0001f4fa); // => 👨
Console.WriteLine(str); // <= Here the Emoji is well displayed

```

**Comment by tig** [comment] 2024-08-19 15:27
Emoji's are not fully supported yet.

They are not supported using `WindowsDriver` at all.

- https://github.com/gui-cs/Terminal.Gui/issues/2616

They are not supported using `CursesDriver` at all. 

- https://github.com/gui-cs/Terminal.Gui/issues/2796

They partially work with `NetDriver`.

Use the CharacterMap scenario, and choose the Emojis Symbols range to see.

Closing as a dupe of the above issues.

**Closed by tig** 2024-08-19 15:27 UTC

**Comment by ChristopheI** [comment] 2024-08-19 15:44
I miss this scenario.

Thank you for your quick answer, you save my day !

**Comment by dodexahedron** [comment] 2024-08-19 17:34
Also good to note that unicode sequences in-line in strings in C# are legal by this syntax, rather than having to call that converter method:

```csharp
string sillyString = "This strings ends with \U0001f4fa";
```

The case of the U is significant, as it dictates whether it interprets the following two or four bytes. Case of the hex doesn't matter.

Capital U considers the next 8 following hex digits as one UTF-32 codepoint (and there must be all 8 digits, with any leading zeros included).  `\U0001F468` -> 👨

Lower-case u considers the next 4 following hex digits ONLY, even if there are 8 digits. As with capital, all 4 must be present.\
It interprets them as a UTF-16 codepoint, which can be the high surrogate in a surrogate pair, as that emoji would require. If you use this for surrogates, you specify both in sequence, high surrogate first: `"\ud83d\udc68"` -> 👨

Invalid code points are immediately known to the compiler as invalid and will be compile errors, which is a major advantage to doing them in-line.

Examples (note: if your console font does not have the required characters, you will see one `?` per UTF-16 char (so `??` for UTF-32 or UTF-16 surrogate pairs):

```csharp
Console.WriteLine ("This line ends with the letter 'a': \u0061");
Console.WriteLine ("This line ends with the string 'e0061': \u00650061");
Console.WriteLine ("This line ends with the letter 'a': \U00000061");
//Console.WriteLine ("This line is a compiler error (invalid codepoint): \U00610065");
Console.WriteLine ("This line ends with the emoji '\ud83d\udc68': \ud83d\udc68");
Console.WriteLine ("This line ends with the emoji '\ud83d\udc68': \U0001F468");
```

**Comment by ChristopheI** [comment] 2024-08-20 07:05
Thank you for this explanation

**Comment by dodexahedron** [comment] 2024-08-21 03:21
Sure thing!

I learned the specifics of the 4-byte case fairly recently, myself, so it was fresh in memory. :)
