### ISSUE TITLE
Raw terminfo-based Linix driver

### ISSUE THREAD

**Issue by migueldeicaza** [gui-cs/Terminal.Gui#84] opened 2018-05-13 19:12 UTC
Currently ncurses poses some problems, Mac ships a misscompiled version (lacks high color support), new features are not available.

Also ncurses mouse support is not great, for example, uncooked mode can not be enabled after a press so drags don't work.  Can be made to work by using lower level events and simulating the rest, but at that point...

Might be good to implement a full driver that can leverage all colors, give full mouse control.

This would also allow me to implement full color support:

https://github.com/migueldeicaza/gui.cs/issues/48

And would address this issue:

https://github.com/migueldeicaza/gui.cs/issues/1

**Comment by klamonte** [comment] 2019-02-27 15:36
Hi,

I've been meaning to connect with y'all.  My apologies if this is an inappropriate venue, but we have some shared interests in terminal/TUI stuff.  (Or if I am repeating myself, I honestly don't remember if I have reached out before.)

Regarding this issue, I have code that successfully handles full mouse clicks/drags and wheel up/down under ncurses, but it requires TERM=xterm-1003 be set before initializing ncurses.  C89 source is in the handle_mouse() function here: https://gitlab.com/klamonte/lcxterm/blob/master/source/input.c .  Code is public domain with CC0 fallback.  (If you desire to run directly on the Linux console with GPM mouse, LCXterm also has code to emit X10 mouse sequences in response to GPM mouse events.)

I also have a Java library that implements a windowing system here: https://jexer.sourceforge.io https://gitlab.com/klamonte/jexer .  The design is quite different from gui.cs, I do not know how many bits are able or worth it to transliterate to C#, but I see a few issues here that touch on some common features.  Also Jexer is able to do its work without using ncurses, termios, or other C functions.  If there is anything there that can help you out please feel free.  Code is MIT licensed.

Again, apologies if this is the wrong forum.  I enjoy this TUI stuff, and am very excited to see this project successfully bringing console/TUI goodness to the C#/.NET world.

**Comment by BDisp** [comment] 2021-06-03 20:58
> Also ncurses mouse support is not great, for example, uncooked mode can not be enabled after a press so drags don't work. Can be made to work by using lower level events and simulating the rest, but at that point...

I think this is already working. I hope the rest is also done someday :-)

**Comment by tig** [comment] 2024-01-04 14:31
Very related: #2610

Also: # (harden EscSeqUtil)

**Comment by tig** [comment] 2024-01-19 15:58
Closing this as a dupe of

- #2610

**Closed** 2024-08-28 05:16 UTC
Labels: enhancement
